nodeLinker: node-modules

npmPublishAccess: public

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: "${NODE_AUTH_TOKEN}"

npmScopes:
  gardenfi:
    npmRegistryServer: "https://registry.npmjs.org/"
