nodeLinker: node-modules

npmPublishAccess: restricted

npmRegistries:
  'https://registry.npmjs.org':
    npmAuthToken: '${NPM_TOKEN}'

npmScopes:
  gardenfi:
    npmRegistryServer: 'https://registry.npmjs.org/'
