yarnPath: .yarn/releases/yarn-4.1.1.cjs

nodeLinker: node-modules
npmPublishAccess: "public"

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: "${NODE_AUTH_TOKEN}"

npmScopes:
  catalogfi:
    npmRegistryServer: "https://registry.npmjs.org/"
