nodeLinker: node-modules

npmPublishAccess: restricted

npmRegistries:
  'https://registry.npmjs.org':
    npmAuthToken: '${NODE_AUTH_TOKEN}'

npmScopes:
  gardenfi:
    npmRegistryServer: 'https://registry.npmjs.org/'
