import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

    home: [
        "Home/home",
        {
            type: "category",
            label: "Introduction",
            items: [
                "Home/Introduction/introduction-to-garden",
                "Home/Introduction/how-to-videos",
            ],
        },
        {
            type: "category",
            label: "Actors",
            link: { type: "doc", id: "Home/Actors/actors" },
            items: [
                "Home/Actors/traders",
                "Home/Actors/integrators",
                "Home/Actors/stakers",
                "Home/Actors/fillers",
            ],
        },
        {
            type: "category",
            label: "Tokenomics",
            link: { type: "doc", id: "Home/Tokenomics/tokenomics" },
            items: ["Home/Tokenomics/revenue-split"],
        },
        {
            type: "category",
            label: "Security",
            link: { type: "doc", id: "Home/Security/security" },
            items: ["Home/Security/bug-bounty", "Home/Security/constraints"],
        },
    ],

    developers: [
        "Developers/developers",
        {
            type: "category",
            label: "API",
            link: { type: "generated-index" },
            items: [{ type: "autogenerated", dirName: "Developers/API" }],
        },
        {
            type: "category",
            label: "SDK",
            link: { type: "doc", id: "Developers/SDK/sdk" },
            items: [{ type: "autogenerated", dirName: "Developers/SDK" }],
        },
    ],

    cookbook: [
        "Cookbook/cookbook",
        {
            type: "autogenerated",
            dirName: "Cookbook",
        },
    ],

    community: [
        "Community/community",
        {
            type: "autogenerated",
            dirName: "Community",
        },
    ],

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
