import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

    home: [
        "home/home",
        {
            type: "category",
            label: "Introduction",
            items: [
                "home/introduction/introduction-to-garden",
                "home/introduction/how-to-videos",
            ],
        },
        {
            type: "category",
            label: "Actors",
            link: { type: "doc", id: "home/actors/actors" },
            items: [
                "home/actors/traders",
                "home/actors/stakers",
                "home/actors/fillers",
            ],
        },
        {
            type: "doc",
            id: "home/tokenomics/tokenomics",
            label: "Tokenomics",
        },
        {
            type: "category",
            label: "Security",
            link: { type: "doc", id: "home/security/security" },
            items: ["home/security/bug-bounty", "home/security/constraints"],
        },
    ],

    developers: [
        "developers/developers",
        {
            type: "category",
            label: "API",
            link: { type: "generated-index" },
            items: [{ type: "autogenerated", dirName: "developers/api" }],
        },
        {
            type: "category",
            label: "Contracts",
            link: { type: "generated-index" },
            items: [{ type: "autogenerated", dirName: "developers/contracts" }],
        },
        {
            type: "category",
            label: "SDK",
            items: [{ type: "autogenerated", dirName: "developers/sdk" }],
        },
    ],

    cookbook: [
        "cookbook/cookbook",
        {
            type: "autogenerated",
            dirName: "cookbook",
        },
    ],

    community: [
        "community/community",
        {
            type: "autogenerated",
            dirName: "community",
        },
    ],

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
