import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

    home: [
        // "home/home",
        // {
        //     type: "category",
        //     label: "Introduction",
        //     items: [
        //         "home/introduction/introduction-to-garden",
        //         "home/introduction/how-to-videos",
        //     ],
        // },
        // {
        //     type: "category",
        //     label: "Actors",
        //     link: { type: "doc", id: "home/actors/actors" },
        //     items: [
        //         "home/actors/traders",
        //         "home/actors/stakers",
        //         "home/actors/fillers",
        //     ],
        // },
        // {
        //     type: "doc",
        //     id: "home/tokenomics/tokenomics",
        //     label: "Tokenomics",
        // },
        // {
        //     type: "category",
        //     label: "Security",
        //     link: { type: "doc", id: "home/security/security" },
        //     items: ["home/security/bug-bounty", "home/security/constraints"],
        // },
        // {
        //     type: "doc",
        //     id: "home/guide",
        //     label: "Garden Brand Guide",
        // }
        "home/get-started",
        "home/roadmap",
        {
            type: "category",
            label: "Basics",
            link: { type: "doc", id: "home/basics/basics" },
            items: [
                {
                    type: "category",
                    label: "Swap",
                    link: { type: "doc", id: "home/basics/swap/swap" },
                    items: ["home/basics/swap/atomic-swaps", "home/basics/swap/order-matching-engine"]
                },
                {
                    type: "category",
                    label: "Stake",
                    link: { type: "doc", id: "home/basics/stake/stake" },
                    items: ["home/basics/stake/governance"]
                },
                "home/basics/liquidity-provision",
                {
                    type: "category",
                    label: "Token",
                    link: { type: "doc", id: "home/basics/token/token" },
                    items: ["home/basics/token/seasons"]
                },
                "home/basics/supported-chains",
                {
                    type: "category",
                    label: "Guides",
                    link: { type: "doc", id: "home/basics/guides/guides" },
                    items: ["home/basics/guides/btc-wbtc", "home/basics/guides/stake-seed", "home/basics/guides/wbtc-btc", "home/basics/guides/wbtc-wbtc"]
                }
            ]
        },
        {
            type: "category",
            label: "Build",
            link: { type: "doc", id: "home/build/build" },
            items: [
                {
                    type: "category",
                    label: "SDK",
                    link: { type: "doc", id: "home/build/sdk/sdk" },
                    items: [
                        "home/build/sdk/installation",
                        "home/build/sdk/quickstart",
                        "home/build/sdk/core-concepts",
                        "home/build/sdk/supported-chains",
                        {
                            type: "category",
                            label: "API Reference",
                            link: { type: "doc", id: "home/build/sdk/api-reference/api-reference" },
                            items: [
                                "home/build/sdk/api-reference/orderbook",
                                "home/build/sdk/api-reference/core"
                            ]
                        },
                        {
                            type: "category",
                            label: "SDK Guides",
                            link: { type: "doc", id: "home/build/sdk/sdk-guides/sdk-guides" },
                            items: [
                                "home/build/sdk/sdk-guides/creating-wallets",
                                "home/build/sdk/sdk-guides/swapping-btc-wbtc",
                                "home/build/sdk/sdk-guides/swapping-wbtc-btc",
                                "home/build/sdk/sdk-guides/1inch-integration"
                            ]
                        }
                    ]
                },
                {
                    type: "category",
                    label: "Cookbook",
                    link: { type: "doc", id: "home/build/cookbook/cookbook" },
                    items: [
                        "home/build/cookbook/cli-tool-with-garden-sdk",
                        {
                            type: "category",
                            label: "Recipes",
                            link: { type: "doc", id: "home/build/cookbook/recipes/recipes" },
                            items: ["home/build/cookbook/recipes/btc-bridge-on-tg"]
                        }
                    ]
                }
            ]
        },
        {
            type: "category",
            label: "Security",
            link: { type: "doc", id: "home/security/security" },
            items: ["home/security/bug-bounty"]
        },
        {
            type: "category",
            label: "Community",
            link: { type: "doc", id: "home/community/community" },
            items: ["home/community/garden-ambassador-program"]
        },
        {
            type: "category",
            label: "FAQs",
            link: { type: "doc", id: "home/faqs/faqs" },
            items: ["home/faqs/support"]
        },
        "home/garden-brand-guide"
    ],

    developers: [
        "developers/developers",
        "developers/core-concepts",
        {
            type: "category",
            label: "API",
            link: { type: "generated-index" },
            items: [{ type: "autogenerated", dirName: "developers/api" }],
        },
        {
            type: "category",
            label: "Contracts",
            link: { type: "generated-index" },
            items: [{ type: "autogenerated", dirName: "developers/contracts" }],
        },
        {
            type: "category",
            label: "SDK",
            items: [{ type: "autogenerated", dirName: "developers/sdk" }],
        },
    ],

    cookbook: [
        "cookbook/cookbook",
        {
            type: "autogenerated",
            dirName: "cookbook",
        },
    ],

    community: [
        "community/community",
        {
            type: "autogenerated",
            dirName: "community",
        },
    ],

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
